repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language: system
        entry: poetry run black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff-check
        args: [--fix]
        language: system
        entry: poetry run ruff check
      - id: ruff-format
        language: system
        entry: poetry run ruff format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        entry: poetry run end-of-file-fixer
      - id: check-yaml
        entry: poetry run check-yaml
      - id: check-toml
        entry: poetry run check-toml

  - repo: https://github.com/pycqa/isort
    rev: 5.11.2
    hooks:
      - id: isort
        name: isort (python)
        language: system
        entry: poetry run isort
